### ISSUE TITLE
Redirect loop on first login

### ISSUE THREAD

**Issue by adamatw** [logicahealth/sandbox-community-edition#6]
I just installed the sandbox community edition on an Ubuntu server following the directions step by step carefully. When I try to access the sandbox in my browser by going to http://sandbox:3001, I get stuck in a redirect loop, where the page keeps redirecting to itself:

![image](https://github.com/logicahealth/sandbox-community-edition/assets/7416891/153fca39-d085-4f08-bf95-c4662b4b79e3)

Every second or two this redirects and reloads. I can connect to the http://keycloak:8080 URL with no problems and access the admin function there, but can't register or get to the login link through the sandbox URL.

**Comment by rlabercrombie** [comment]
I happened to get the same issue.  When opening up developer tools to the console and ensuring the logs remained, it appeared that there was an outgoing request to stu3/metadata.  If you open up the docker-compose file and uncomment the sections related to stu3, you should be able to get past the redirect loop.

**Comment by janstadt** [comment]
Did this work for anyone? I have the container uncommented as well as the `API_STU3_HOST=stu3` uncommented now and its still doing the redirect loop. The logs for the stu3 container dont tell me much of anything.

**Comment by rlabercrombie** [comment]
It's been a little while since I've dove into this, but if I recall I got a clue into the request that was erroring out in the browser developer console logs, rather than container logs.  While redirects generally replace the developer console logs by default, theres a developer tool console option you can click on to keep them regardless.  

But long story short there, is that if there's a <version>/metadata request thats causing an issue and you arent looking to use that specific version (ie. you only care about r4 and dstu2 or stu3 metadata calls are giving issues, then you can comment out that section in the docker-compose file, including the entire block with the version label and the API_<version>_HOST line as @janstadt mentioned.  

If I get a chance I'll take a look tonight, but otherwise feel free to reach out again in this thread (or richard.abercrombie@palmettogbaservices.com) 

Just to make sure, what branch/commit are you using?

**Comment by preston** [comment]
@rlabercrombie Would you mind submitting a PR? I'd be happy to merge that in immediately!

**Comment by rlabercrombie** [comment]
@preston  I did have a chance to test a little tonight.  I was misremembering, *uncommenting* stu3 sections in docker-compose previously solved the issue of redirects, which it looks like that change was pushed to master already anyhow.   (Deleting my last comment to avoid confusion). 

I'd be curious to hear if @VijayaraghavanPS or @janstadt are getting the redirect errors or are experiencing a different issue.

**Comment by VijayaraghavanPS** [comment]
Hi @rlabercrombie , I cloned the repo and did docker compose up without making any changes in docker-compose file (dstu2 is commented out in that). When i opened http://localhost:3001/ it kept on refreshing the page in a loop without redirecting anywhere. I then tried uncommenting the line - API_STU3_HOST=stu3 from the sandbox-manager-api section. I also tried uncommenting the section of dstu2, but the result was same.

**Comment by preston** [comment]
@diegokaminker How did you fix the redirect issue on your local environment?

**Comment by diegokaminker** [comment]
Hi
1) I uncommented the STU3 content of the docker-compose file
2) I replaced keycloak with sleighzy/keycloak because I have a mac M2
This is my docker-compose and an image from my local sandbox console working

version: "3"

volumes:
  logica-sandbox-volume:

services:

  keycloak:
    image: sleighzy/keycloak

    volumes:
      - "./realm_properties.json:/etc/security/realm_properties.json"
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=/etc/security/realm_properties.json
    command:
      [
        "-Djboss.http.port=8080",
        "-Dkeycloak.profile.feature.upload_scripts=enabled",
      ]

  sandbox-mysql:
    image: logicahealth/sandbox-mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - logica-sandbox-volume:/var/lib/mysql57
    environment:
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    command: ['mysqld', '--default-authentication-plugin=mysql_native_password']
    healthcheck:
      test: ["CMD-SHELL", "/wait-for-db.sh"]
      interval: 10s
      timeout: 60s
      retries: 50

  sandbox-manager-api:
    image: logicahealth/sandbox-manager-api:latest
    ports:
      - "12000:12000"
    environment:
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_NAME=sandman
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      # - API_DSTU2_HOST=dstu2
      # - API_STU3_HOST=stu3
      - API_R4_HOST=r4
      - API_R5_HOST=r5
    restart: unless-stopped
    depends_on:
    - sandbox-mysql

  sandbox:
    image: logicahealth/sandbox:latest
    ports:
      - "3000:3000"
      - "3001:3001"
      - "8060:8060"
    environment:
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - DB_NAME=oic
      - DB_HOST=sandbox-mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - SHOW_SQL=true
      - API_DSTU2_HOST=dstu2
      - API_DSTU2_PORT=8078
      - API_STU3_HOST=stu3
      - API_STU3_PORT=8079
      - API_R4_HOST=r4
      - API_R4_PORT=8070
      - PATIENT_PICKER_HOST=localhost
      - PATIENT_PICKER_PORT=8094
      - SANDMAN_API_HOST=sandbox-manager-api
      - SANDMAN_API_PORT=12000
      - SPRING_PROFILES_ACTIVE=users-keycloak,local
      - KEYCLOAK_REALM=Development
      - KEYCLOAK_AUTH_SERVER_URL=http://keycloak:8080/auth
      - KEYCLOAK_SSL_REQUIRED=none
      - KEYCLOAK_CREDENTIALS=593ada9c-b1dc-444f-a2e6-30cc4add8146
      - KEYCLOAK_LOGOUT_SUCCESS_URL=http://keycloak:8080/auth/realms/Development/protocol/openid-connect/logout?redirect_uri=http://localhost:3001
      - JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,address=5060,server=y,suspend=n"
    restart: unless-stopped
    depends_on:
    - sandbox-mysql

  # dstu2:
  #   image: logicahealth/api:latest
  #   ports:
  #     - "8078:8078"
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=dstu2,multitenant
  #     - API_PORT=8078
  #     - SANDBOX_NAME=hspc8
  #     - SBMA_HOST=sandbox-manager-api
  #     - SBMA_PORT=12000
  #     - DB_HOST=sandbox-mysql
  #     - DB_PORT=3306
  #     - DB_USER=root
  #     - DB_PASSWORD=password
  #     - AUTH_HOST=sandbox
  #     - AUTH_PORT=8060
  #     - MANIFEST_OVERRIDE=false
  #   depends_on:
  #     sandbox-mysql:
  #       condition: service_healthy

  stu3:
   image: logicahealth/api:latest
   ports:
    - "8079:8079"
   environment:
     - SPRING_PROFILES_ACTIVE=stu3,multitenant
     - API_PORT=8079
     - SANDBOX_NAME=hspc9
     - SBMA_HOST=sandbox-manager-api
     - SBMA_PORT=12000
     - DB_HOST=sandbox-mysql
     - DB_PORT=3306
     - DB_USER=root
     - DB_PASSWORD=password
     - AUTH_HOST=sandbox
     - AUTH_PORT=8060
     - MANIFEST_OVERRIDE=false
   restart: unless-stopped
   depends_on:
   - sandbox-mysql

  r4:
    image: logicahealth/api:latest
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=r4,multitenant
      - API_PORT=8070
      - SANDBOX_NAME=hspc10
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    restart: unless-stopped
    depends_on:
    - sandbox-mysql

  r5:
    image: logicahealth/api:latest
    ports:
      - "8071:8071"
    environment:
      - SPRING_PROFILES_ACTIVE=r5,multitenant
      - API_PORT=8071
      - SANDBOX_NAME=hspc11
      - SBMA_HOST=sandbox-manager-api
      - SBMA_PORT=12000
      - DB_HOST=sandbox-mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password
      - AUTH_HOST=sandbox
      - AUTH_PORT=8060
      - MANIFEST_OVERRIDE=false
    restart: unless-stopped
    depends_on:
    - sandbox-mysql

  static-content:
    image: logicahealth/sandbox-ce-static-content:latest
    ports:
      - "8090:80"

  bilirubin-risk-chart:
    image: logicahealth/bilirubin-risk-chart-app:latest
    ports:
      - "8086:8086"

  patient-data-manager:
    image: logicahealth/patient-data-manager:latest
    ports:
      - "8096:8096"
![MyLocalSandbox](https://github.com/logicahealth/sandbox-community-edition/assets/14879517/563708f6-e49b-4e53-b1a6-8ba8b940f561)

**Comment by preston** [comment]
@diegokaminker Could you attach the .yml file? I'll test it on linux/x64 and, if it works, update the master branch.

**Comment by preston** [comment]
@VijayaraghavanPS @adamatw @janstadt @rlabercrombie I just validated that @diegokaminker 's fixes work on my macOS M3 machine, and have committed the changes to master, in additional to clarifying that the hosts files entries are *required*. If you continue to experience redirect loops, please make sure you have correctly added hosts file entries as indicated, here: https://github.com/logicahealth/sandbox-community-edition/blob/d84ba3d218cc7618d481efcdf94ea22294e0cf1e/README.md?plain=1#L211

Please reopen if this is still an issue!
